### ISSUE TITLE
Any idea how to find easily values of (deeply) nested keys, when the keys not always exist?

### ISSUE THREAD

**Issue by halloleo** [kellyjonbrazil/jello#30]
I have a JSON file like this:

```
{"details": {
  "sections": [
    {"fields": [
      { "x": "don't", "v": "Yes!" },
      { "x": "don't", "w": "don't" }
    ]},
    {"fields": [
      { "x": "don't", "v": "Indeed!" },
    ]}],
  "other-stuff": "don't"}
}
```

I need to extract the values to the `"v"` keys, i.e _"Yes!"_ and _"Indeed!"_ Because the `"v"` key is not always present, I do something like this:

```
cat data.json | jello -c '\
res = []
for s in _.details.sections:
    for f in s.fields:
        try:
            res.append(f.v)
        except KeyError:
            pass
res'
```

This works, but feels pretty cumbersome. Is there a  way to gather the values easier then with my approach? Also it would be nice if I didn't need to know how deep my `"v"` keys are located.

**Comment by kellyjonbrazil** [comment]
Hi there - I'm going to convert this issue into a Discussion. I'll provide more info over there.
