### ISSUE TITLE
'<' not supported between instances of 'DotMap' and 'DotMap'

### ISSUE THREAD

**Issue by ibeex** [kellyjonbrazil/jello#36]
trying sorting `ps` output I get this error.

```txt
❯ ps auxwww | jc --ps | jello 'sorted(_)'
jello:  Query Exception:  TypeError
        '<' not supported between instances of 'DotMap' and 'DotMap'
        query: sorted(_)
        data: [{'user': 'root', 'pid': 1, 'vsz': ... ercent': 0.0, 'mem_percent': 0.0}]
```

**Comment by kellyjonbrazil** [comment]
Hi there!

In Python you cannot sort a list of dictionaries in that way. Which field in the dictionaries do you want to sort on?

> Note: `DotMap` is a `dict`-like object in `jello` and works the same way, except it allows dot-notation. `jello` converts all dictionaries to `DotMap` objects.

**Comment by ibeex** [comment]
thx, I was sure that I tried
`ps auxwww | jc --ps | jello 'sorted(_, key=lambda x: x.rss, reverse=True)'` 

this works

**Comment by kellyjonbrazil** [comment]
Excellent! By the way, you might also try `jellex` which is a TUI wrapper for `jello` and allows you to interactively query the JSON and it displays the results immediately. It can make crafting a query much faster and easier.

<img width="978" alt="jellex-screenshot" src="https://user-images.githubusercontent.com/24423665/125111615-f8483800-e09a-11eb-8774-9870fc2ac2fa.png">

Here's a demo video: https://youtu.be/9VCXjINa74E

It can be installed via `pip`:
```
pip install jellex
```
