### ISSUE TITLE
[FEATURE REQUEST] Fedora RPM

### ISSUE THREAD

**Issue by blaisep** [kellyjonbrazil/jello#40]
Hi @kellyjonbrazil ,
This is a placeholder note for the goal of adding `jello` to the fedora build system, similar to the way [jc](https://src.fedoraproject.org/rpms/jc.git) is included in [Koji](https://koji.fedoraproject.org/koji/packageinfo?packageID=31415)

**Comment by kellyjonbrazil** [comment]
If anyone can help getting jello packaged for Fedora, please let me know. Thanks!

**Comment by musicinmybrain** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2059247

**Comment by kellyjonbrazil** [comment]
Huge thanks @musicinmybrain!
