### ISSUE TITLE
Failure to call `main()` in cli.py:211-212 causes `python -m jello.cli` to be a no-op

### ISSUE THREAD

**Issue by autumnjolitz** [kellyjonbrazil/jello#49]
Issue: https://github.com/kellyjonbrazil/jello/blob/0bba08af813a2783cea602992255b487bef46556/jello/cli.py#L211-L212

The purpose of making `python -m jello.cli` work is that it allows for per-interpreter, virtualenv and venv installs to be used by referencing the interpreter.

However due to the use of a `pass` instead of:
```
if __name__ == "__main__":
    main()
```

It is not possible to use jello without letting it stomp into the `$PATH`

Remediation:

- replace `pass` with `main()`
- alternatively you can add a `__main__.py` file and have it call `jello.cli.main()` after an `import jello.cli` - that would make `python -m jello` work which satisfies the Principle Of Least Astonishment

**Comment by kellyjonbrazil** [comment]
Thanks for the heads up! I'll make sure to do this on `jc` and `jtbl`, too. Might be able to work on this over the weekend.

**Comment by kellyjonbrazil** [comment]
I made the changes and uploaded to pypi (v1.5.4). Let me know if you run into any other issues. Thanks!

**Comment by autumnjolitz** [comment]
Confirmed fixed! Thank you!

```
(cpython37) InvincibleReason:~$ python -m pip install -U jello==1.5.4
Collecting jello==1.5.4
  Using cached jello-1.5.4-py3-none-any.whl (17 kB)
Requirement already satisfied: Pygments>=2.4.2 in ./.virtualenvs/cpython37/lib/python3.7/site-packages (from jello==1.5.4) (2.12.0)
Installing collected packages: jello
Successfully installed jello-1.5.4
(cpython37) InvincibleReason:~$
(cpython37) InvincibleReason:~$ echo '{"field": [{"hello!": "jello"}]}' | python -m jello '_.field[0]["hello!"]'
"jello"
(cpython37) InvincibleReason:~$ echo '{"field": [{"hello!": "jello"}]}' | python -m jello.cli '_.field[0]["hello!"]'
"jello"
(cpython37) InvincibleReason:~$
```
