### ISSUE TITLE
Web demo is down

### ISSUE THREAD

**Issue by RenHoekNL** [kellyjonbrazil/jello#56]
https://jello-web-demo.herokuapp.com/ gives

> Application error
> 
> An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
> heroku logs --tail

**Comment by kellyjonbrazil** [comment]
Hi there! Sorry, I took the jello web demo off of Heroku due to hosting pricing changes. It looks like I forgot to update the link in the README. That should be fixed now. Here is the new link:
https://jello-web.onrender.com
